services:
  postgres:
    container_name: postgres-sql-spring-app
    ime: postgres:17.5
    environment:
      POSTGRES_USER: sekhar
      POSTGRES_PASSWORD: sekhar
      PGDATA: /data/postgres
      POSTGRES_DB: spring_app_db
    volum:
      - postgres:/data/postgres
    pots:
      - "5432:5432"
    resrt: unless-stopped
volmes:
  postgres:


