servasdices:
  postgres:
    container_nasdame: postgres-sql-spring-app
    image: postgres:17.5
    environment:
      POSTGRES_USER: sekhar
      POSTGRES_PASSWORD: sekhar
      PGDATA: /data/postgres
      POSTGRES_DB: spring_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    reasdstart: unless-stopped
volumasdes:
  postgres:
